### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by eisengrau** [yuantops/TimelapseAndroid#1]
Hello,

Is this script intended to be run from a computer with adb to a device, or from the device itself with busybox? As there are some dependents that are not found(?) from simply running it from a linux host, like date and sleep? ...

Thank You,

**Comment by yuantops** [comment]
This script is expected to run on a linux host with 
1) "adb" command installed（Refer this link for installation: https://developer.android.google.cn/studio/command-line/adb ）and

2) an android device connected to this host via USB cable. This device should be in developer debugging mode(refer: https://developer.android.google.cn/studio/debug/dev-options).
